name: Build Gram Shreema APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android SDK
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-36"
          sdkmanager "build-tools;36.0.0"

      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.7

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Check APK
        run: |
          ls -lh app/build/outputs/apk/debug/
          $ANDROID_HOME/build-tools/36.0.0/aapt dump badging app/build/outputs/apk/debug/app-debug.apk | grep -E "package:|launchable-activity:"
                    unzip -l app/build/outputs/apk/debug/app-debug.apk | grep classes.dex

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gram-shreema-debug-apk-check
          path: "**/build/outputs/apk/debug/*.apk"
